version: "2"
services:
  db:
    hostname: db
    image: mongo
    restart: always
    expose:
    - "27017"
    ports:
    - 27017:27017
  backend:
    hostname: backend
    environment:
      - ADMIN_EMAIL=
      - ADMIN_PW=
      - SECRET=
      - DB_HOST=db
      - DB_NAME=cPark
      - PORT=8080
    restart: on-failure
    depends_on:
      - db
    build: ./backend
    links:
    - db
    ports:
    - 8080:8080
  frontend:
    environment:
      - HTTP_PROXY=http://backend:8080
    restart: on-failure
    depends_on:
      - backend
    build: ./frontend
    ports:
    - 3000:3000
    links:
    - backend